name: Build exe

on:
  workflow_dispatch:

  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: setup
        run: python setup.py

      - name: Download Go dependencies
        run: go mod tidy

      - name: Build Go shared library
        run: go build -o SysInfo.exe

      - name: requets
        run: python -m pip install pywin32 requests pycryptodomex pyinstaller

      - name: build exe
        run: pyinstaller --onefile --add-data "SysInfo.exe;." main.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: |
              ./dist/main.exe
