name: Test the package by runing it using go run

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: idk
        run: python setup.py

      # Step 3: Download Go dependencies
      - name: Download Go dependencies
        run: go mod tidy

      # Step 4: Build Go shared library
      - name: Build Go shared library
        run: go run main.go
